app/blueprints/fight/__init__.py
from flask import Blueprint

bp = Blueprint('fight', __name__, url_prefix='/fight')

from . import routes

app/blueprints/fight/routes.py
from flask import redirect, url_for, render_template, g, request, flash
from flask_login import login_required
from app.forms import SearchForm
from app.models import User
from app import app
from . import bp as fight

@app.before_request
def before_request():
     g.usf = SearchForm()

@fight.route('/fight/<username>')
@login_required
def fight_user():
    pass

@fight.route('/search-profile/<username>')
@login_required
def search_profile(username):
    user = User.query.filter_by(username=username).first()
    userlist = User.query.all()
    return render_template('search_profile.jinja', user = user, form = g.usf, userlist = userlist)
    
@fight.post('/usersearch')
def usersearch():
    return redirect(url_for('fight.search_profile', username = g.usf.searchfield.data))

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokemonline</title>
    <link rel="stylesheet" href="{{ url_for('static', filename = 'main.css') }}">
</head>
<body>
    <nav>
        {% include "navbar.jinja" %}
    </nav>
    <main>
    {% if current_user.is_authenticated %}
        <p>Logged in as {{ current_user.username }}</p>
    {% endif %}
    {% for message in get_flashed_messages() %}
        <p style="color: red;">{{ message }}</p>
    {% endfor %}
    {% block content %}
    
    {% endblock content %}
    </main>
</body>
</html>

app/templates/fight.jinja
{# Must display pokemon in battle #}

{% include "base.jinja" %}

app/templates/index.jinja
{% include "base.jinja" %}
<h1>Welcome to Pokemonline!</h1>
<p>Battle against other players or go catch your own pokemon!</p>
{% if current_user.is_authenticated %}
<form action="{{ url_for('fight.usersearch') }}" method="POST">
    <h4>Search for user to battle!</h4>
    {{ g.usf.hidden_tag() }}
    {{ g.usf.searchfield() }}
    {{ g.usf.submit() }}
</form>
<form action="{{ url_for('find.pokesearch') }}" method="POST">
    <h4>Search for a pokemon to catch!</h4>
    {{ form_poke.hidden_tag() }}
    {{ form_poke.searchfield() }}
    {{ form_poke.submit() }}
</form>
{% else %}
<p>To begin playing, you must either Sign Up or Sign In.</p>
<form action="" method="POST">
    <input type="submit" name="signup" value="Sign up">
</form>
<p>--OR--</p>
<form action="" method="POST">
    <input type="submit" name="signin" value="Sign in">
</form> 

{% endif %}

app/templates/navbar.jinja
{% if current_user.is_authenticated %}
<ul>
    <li><a href="{{ url_for('main.home') }}">Home</a></li>
    <li><a href="{{ url_for('auth.signout') }}">Sign Out</a></li>
    <li><a href="{{ url_for('user.profile') }}">My Profile</a> ({{ current_user.username }})</li>
</ul>
{% else %}
<ul>
    <li><a href="{{ url_for('main.home') }}">Home</a></li>
    <li><a href="{{ url_for('auth.signup') }}">Sign Up</a></li>
    <li><a href="{{ url_for('auth.signin') }}">Sign In</a></li>
</ul>
{% endif %}

app/templates/pokemon.jinja
{# displays pokemon and pokemon's stats #}
<p>
        <img src="{{ poke.fr_sprite }}" alt="poke.name">
        <p>Name: {{ poke.name }} </p>
        <span> Level: {{ poke.level }}</span>
        <p> Type: {{ poke.first_type }}
        {% if poke.second_type %}
            , {{ poke.second_type }}
        {% endif %}
        </p>
    </p>

app/templates/profile.jinja
{# displays user's info and their pokemon and the pokemon's info #}
{% extends "base.jinja" %}

{% block content %}
{% if user %}
    <h4>{{ user.username }}</h4>
    <p>(trainer since {{ user.joined }})</p>
    <p>Leaderboard score: {{ user.score }}</p>
    {% for poke in user.my_poke %}
        {% include "pokemon.jinja" %}
        <form action="{{ url_for('user.delete_pokemon', poke_id=poke.poke_id) }}" method="POST">
            <input type="submit" value="DELETE">
        </form>
    {% endfor %}
{% endif %}

{% endblock content %}

app/templates/search_pokemon.jinja
{% include "base.jinja" %}

{% block content %}
<form action="{{ url_for('find.pokesearch') }}" method="POST">
    <h3>Search for pokemon by name</h3>
    {{ form.hidden_tag() }}
    {{ form.searchfield() }}
    {{ form.submit() }}
</form>
{% if poke %}
    {% include "pokemon.jinja" %}
    <form action="" method="POST">
        <input type="submit" name="{{poke.poke_id}}" value="Capture">
    </form>
{% else %}
    <h5>Pokemon does not exist</h5>
{% endif %}

{% endblock content %}

app/templates/search_profile.jinja
{% extends "base.jinja" %}

{% block content %}
<form action="{{ url_for('fight.usersearch') }}" method="POST">
    <h3>Search for user by username</h3>
    {{ form.hidden_tag() }}
    {{ form.searchfield() }}
    {{ form.submit() }}
</form>
{% if user %}
    <h4>{{ user.username }}</h4>
    <p>(trainer since {{ user.joined }})</p>
    <p>Leaderboard score: {{ user.score }}</p>
    {% for poke in user.my_poke %}
        {% include "pokemon.jinja" %}
        <form action="" method="POST">
            <input type="submit" name="{{poke.poke_id}}" value="FIGHT">
        </form>
    {% endfor %}

{% else %}
    <h5>User does not exist</h5>
    <p>All users</p>
    {% for u in userlist %}
        {{u.username}} <br>
    {% endfor %}
{% endif %}

{% endblock content %}

app/templates/signin.jinja
{% extends "base.jinja" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="POST" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }} <br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }} <br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.remember_me.label }} <br>
            {{ form.remember_me() }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock content %}

app/templates/signup.jinja
{% extends "base.jinja" %}

{% block content %}
    <h1>Sign Up</h1>
    <form action="" method="POST" novalidate>
        {{ form.hidden_tag() }}
        <p>
        {{ form.username.label }} <br>
        {{ form.username(size=32) }}
        {% for error in form.username.errors %}
            <span>{{ error }}</span>
        {% endfor %}
        </p>
        <p>
        {{ form.email.label }} <br>
        {{ form.email(size=32) }}
        {% for error in form.email.errors %}
            <span>{{ error }}</span>
        {% endfor %}
        </p>
        <p>
        {{ form.password.label }} <br>
        {{ form.password(size=32) }}
        {% for error in form.password.errors %}
            <span>{{ error }}</span>
        {% endfor %}
        </p>
        <p>
        {{ form.reenter_password.label }} <br>
        {{ form.reenter_password(size=32) }}
        {% for error in form.reenter_password.errors %}
            <span>{{ error }}</span>
        {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock content %}